apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3.8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: souroot#1423
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: UserBlog      
        - name: MYSQL_PASSWORD
          value: PwdBlog   
        resources:
            requests:
              cpu: 500m
              memory: 128M
            limits:
              cpu: 1000m
              memory: 512M                   
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mariadb-volume
      volumes:
        - name: mariadb-volume
          persistentVolumeClaim:
              claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-mariadb
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-wordpress
spec:  
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: service-mariadb
        - name: WORDPRESS_DB_USER
          value: UserBlog
        - name: WORDPRESS_DB_PASSWORD
          value: PwdBlog  
        volumeMounts:
          - mountPath: "/var/www/html"
            name: wpvolume
        resources:
            requests:
              cpu: 500m
              memory: 128M
            limits:
              cpu: 1000m
              memory: 128M
      volumes:
        - name: wpvolume
          persistentVolumeClaim:
              claimName: wordpress-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

