apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-wordpress
spec:  
  selector:
    matchLabels:
      app: deploywordpress
  template:
    metadata:
      labels:
        app: deploywordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: service-mariadb
        - name: WORDPRESS_DB_USER
          value: UserBlog
        - name: WORDPRESS_DB_PASSWORD
          value: PwdBlog  
        volumeMounts:
          - mountPath: "/var/www/html"
            name: wpvolume
      volumes:
        - name: wpvolume
          persistentVolumeClaim:
              claimName: wordpress-azurefile

